/*
 * TRANSLATION FILE (GERMAN)
 *
 * Alternative to stringtable.csv which is simpler to install for the mission maker.
 * The token ""%1"" represents a dynamic value generated by the scripts, like a vehicle name.
 */

STR_R3F_LOG_action_heliporter = "Objekt einhaken";
STR_R3F_LOG_action_heliporter_fact = """%1"" eingehakt.";
STR_R3F_LOG_action_heliport_dump = "Objekt ausklinken";
STR_R3F_LOG_action_heliport_dump_fact = """%1"" ausgeklinkt.";
STR_R3F_LOG_action_heliport_waiting = "Wird eingehakt... (%1)";
STR_R3F_LOG_action_heliport_failed_hold = "Einhaken abgebrochen! Verbleibe im Schwebeflug während des Vorgangs.";

STR_R3F_LOG_action_move_object = """%1"" aufnehmen";
STR_R3F_LOG_action_release_object = """%1"" ablegen";
STR_R3F_LOG_action_align_slope = "An die Neigung anpassen";
STR_R3F_LOG_action_aligner_sol = "An den Boden anpassen";
STR_R3F_LOG_action_aligner_horizon = "Horizontal anpassen";
STR_R3F_LOG_action_tourner = "Links/Rechts drehen (X / C Tasten)";
STR_R3F_LOG_action_rapprocher = "Näher/Weiter (F / R Tasten)";
STR_R3F_LOG_ne_pas_monter_dans_vehicule = "Du kannst in das Fahrzeug nicht einsteigen während du dieses Objekt trägst!";

STR_R3F_LOG_action_load_moves = "In Fahrzeug einladen";
STR_R3F_LOG_action_select_object_load = """%1"" einladen...";
STR_R3F_LOG_action_load_selection = "...einladen in ""%1""";
STR_R3F_LOG_action_selectionner_object_fait = "Wähle das Ziel für das Einladen von""%1""...";
STR_R3F_LOG_action_load_in_course = "Lade ein...";
STR_R3F_LOG_action_charger_fait = """%1"" wurde in ""%2"" eingeladen.";
STR_R3F_LOG_action_charger_pas_assez_de_place = "Es ist nicht genug Platz für dieses Objekt in diesem Fahrzeug!";

STR_R3F_LOG_action_tow_direct = """%1"" abschleppen";
STR_R3F_LOG_action_tow_moves = "Objekt abschleppen";
STR_R3F_LOG_action_detach = "Objekt vom Schleppseil lösen";
STR_R3F_LOG_action_detach_fait = "Objekt vom Schleppseil gelöst.";
STR_R3F_LOG_action_detach_impossible_pour_ce_vehicule = "Nur der Pilot kann das Objekt vom Schleppseil lösen.";

STR_R3F_LOG_action_content_vehicle = "Fahrzeugfracht anzeigen.";
STR_R3F_LOG_action_decharger_en_cours = "Abladen läuft...";
STR_R3F_LOG_action_decharger_fait = """%1"" wurde aus dem Fahrzeug abgeladen.";
STR_R3F_LOG_action_decharger_deja_fait = "Das Objekt wurde bereits abgeladen!";
STR_R3F_LOG_action_decharger_deplacable_exceptionnel = "Einmal platziert wird dieses Objekt nicht mehr manuell bewegbar sein.<br/>Aktion bestätigen?";

STR_R3F_LOG_action_ouvrir_factory = "Fabik öffnen";
STR_R3F_LOG_action_creer_en_cours = "Herstellung läuft...";
STR_R3F_LOG_action_creer_fait = """%1"" wurde hergestellt.";
STR_R3F_LOG_action_creer_pas_assez_credits = "Die Fabrik verfügt nicht über genug Credits, um dieses Objekt herzustellen.";
STR_R3F_LOG_action_revendre_factory_direct = """%1"" zurück in die Fabrik geben";
STR_R3F_LOG_action_resell_factory_moves = "In die Fabrik zurückgeben";
STR_R3F_LOG_action_revendre_factory_selection = "...in die Fabrik zurückgeben";
STR_R3F_LOG_action_revendre_en_cours = "Rückgabe in die Fabrik...";
STR_R3F_LOG_action_revendre_fait = """%1"" wurde in die Fabrik zurückgegeben.";
STR_R3F_LOG_action_revendre_decharger_avant = "Du kannst es nicht zurückgeben, da der Frachtinhalt nicht leer ist!";

STR_R3F_LOG_mutex_action_en_cours = "Die momentane Aktion ist nicht beendet!";
STR_R3F_LOG_player_dans_object = "Es ist ein Spieler in dem Objekt ""%1"" !";
STR_R3F_LOG_object_in_course_transport = """%1"" wird bereits bewegt!";
STR_R3F_LOG_object_remorque_en_cours = "Unmöglich, da das Objekt ""%1"" ein anderes schleppt!";
STR_R3F_LOG_trop_loin = "Unmöglich, da das Objekt ""%1"" zu weit entfernt ist!";

STR_R3F_LOG_dlg_CV_titre = "Fahrzeugfrachtraum";
STR_R3F_LOG_dlg_CV_capacite_vehicule = "Beladung: %1/%2";
STR_R3F_LOG_dlg_CV_btn_decharger = "ABLADEN";
STR_R3F_LOG_dlg_CV_btn_fermer = "ABBRECHEN";

STR_R3F_LOG_dlg_LO_titre = "Fabrik";
STR_R3F_LOG_dlg_LO_credits_restants = "Verbleibende Credits: %1";
STR_R3F_LOG_dlg_LO_btn_creer = "HERSTELLEN";
STR_R3F_LOG_dlg_LO_btn_fermer = "ABBRECHEN";

STR_R3F_LOG_name_fonctionnalite_proprietes = "Eigenschaften";
STR_R3F_LOG_name_fonctionnalite_side = "Seite";
STR_R3F_LOG_name_fonctionnalite_places = "Sitze";
STR_R3F_LOG_name_fonctionnalite_passif = "Es kann:";
STR_R3F_LOG_name_fonctionnalite_passif_deplace = "vom Spieler bewegt werden";
STR_R3F_LOG_name_fonctionnalite_passif_heliporte = "angehängt werden";
STR_R3F_LOG_name_fonctionnalite_passif_remorque = "abgeschleppt werden";
STR_R3F_LOG_name_fonctionnalite_passif_transporte = "transportiert werden";
STR_R3F_LOG_name_fonctionnalite_passif_transporte_capacite = "Frachtplatzverbrauch %1";
STR_R3F_LOG_name_fonctionnalite_actif = "Es kann:";
STR_R3F_LOG_name_fonctionnalite_actif_heliporte = "Anhängen";
STR_R3F_LOG_name_fonctionnalite_actif_remorque = "Abschleppen";
STR_R3F_LOG_name_fonctionnalite_actif_transporte = "Transportieren";
STR_R3F_LOG_name_fonctionnalite_actif_transporte_capacite = "Frachtplatz %1";

STR_R3F_LOG_deverrouillage_en_cours = "Entsperren... (%1)";
STR_R3F_LOG_deverrouillage_echec_attente = "Entsperrung abgebrochen! Fixiere das Objekt während des Countdowns.";
STR_R3F_LOG_deverrouillage_succes_attente = "Objekt entsperrt.";
STR_R3F_LOG_action_unlock = """%1"" entsperren";
STR_R3F_LOG_action_unlock_impossible = "Object gesperrt";